//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birdbrained.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird
    {
        public System.Guid Id { get; set; }
        public string EnglishName { get; set; }
        public string Class { get; set; }
        public string Order { get; set; }
        public string Family { get; set; }
        public string Subfamily { get; set; }
        public string Genus { get; set; }
        public string Species { get; set; }
        public string LearnMoreHyperlink { get; set; }
        public string Photo { get; set; }
    }
}
